name: Node.js CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30
  steps:
    - name: Execute remote commands via SSH
      timeout-minutes: 40
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 3.239.72.176
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Starting 29-minute stability test..."
          sleep 1740 # 29 хвилин у секундах
          echo "Testing if connection is still alive..."
          cd /var/www/pm2/source
          git pull origin main
          sudo npm install --production
          pm2 restart all
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      timeout-minutes: 30
      uses: actions/checkout@v4

    - name: Execute remote commands via SSH
      timeout-minutes: 30
      uses: appleboy/ssh-action@v1.0.3 # Use a reliable SSH Action
      with:
        host: 3.239.72.176
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

        script: |
          cd /var/www/pm2/source
          git pull origin main
          sudo npm install --production
          pm2 restart all
